#debug: true

#dataSource
dataSource:
  driver: org.mariadb.jdbc.Driver
  #jdbcUrl: jdbc:mysql://211.238.242.180/anypoint_test?characterEncoding=utf8&amp;useUnicode=true&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull
  jdbcUrl: jdbc:mysql://211.110.154.197/anypoint?characterEncoding=utf8&amp;useUnicode=true&amp;autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull
  username: amg
  password: '*emflaj*'

#kafka
kafka:
  metadata.broker.list: localhost:9092,localhost:9093
  zookeeper:
    url: localhost:2181
    session.timeout.ms: 4000
    sync.timeout.ms: 200
  auto.commit.interval.ms: 1000
  group.id: anypoint.tv.group
  topic:
      log.collector: log.collector.test.0001
      log.collector.thread.nums: 4
      realtime.analytics: realtime.analytics.test.0001
      realtime.analytics.thread.nums: 4

#log-impresson
log.impression:
  csv.file.path: /tmp/csv/impresson-log/
  table.name:
    genre: ImpressionLogGenre
    period: ImpressionLogPeriod
    region: ImpressionLogRegion
    campaign.genre: ImpressionLogCampaignGenre
    campaign.period: ImpressionLogCampaignPeriod
    campaign.region: ImpressionLogCampaignRegion

#logging
logging.config: classpath:logback-test.xml